# Generated by Django 2.1.4 on 2018-12-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_auto_20181221_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='count_comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tag',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='count_posts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='count_tags',
            field=models.IntegerField(default=0),
        ),
    ]
